--[[
    Constants used in the game
]]

VIRTUAL_WIDTH = 384
VIRTUAL_HEIGHT = 216

BUTTON_HEIGHT = 64

WINDOW_WIDTH = 800
WINDOW_HEIGHT = 600


TILE_SIZE = 16
-- entity
PLAYER_WALK_SPEED = 60
PLAYER_RUN_SPEED = 100

-- map stuff
MAP_WIDTH = VIRTUAL_WIDTH / TILE_SIZE - 2
MAP_HEIGHT = 60
--MAP_HEIGHT = math.floor(VIRTUAL_HEIGHT / TILE_SIZE) - 2  -- THIS DOESN'T WORK. a set value of 60 works for my computer at least

MAP_RENDER_OFFSET_X = (VIRTUAL_WIDTH - (MAP_WIDTH * TILE_SIZE)) / 2
MAP_RENDER_OFFSET_Y = (VIRTUAL_HEIGHT - (MAP_HEIGHT * TILE_SIZE)) / 2

    

    